"""Auth domain constants."""

# Error codes
ERROR_INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
ERROR_TOKEN_MISSING = "TOKEN_MISSING"
ERROR_TOKEN_EXPIRED = "TOKEN_EXPIRED"
ERROR_AUTH_FAILED = "AUTH_FAILED"
